# Generated by Django 6.0.2 on 2026-02-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dish",
            old_name="ingredients",
            new_name="ingredient",
        ),
    ]
