# Generated by Django 6.0.2 on 2026-02-13 08:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_rename_ingredients_dish_ingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Price of the dish",
                max_digits=8,
            ),
        ),
    ]
